[workspace]

resolver = "2"
members = [
    "crates/highlights",
    "crates/kyac",
    "crates/kyanite",
    "crates/runtime", 
    "crates/subprocess"
]
default-members = [
    "crates/kyanite",
    "crates/runtime"
]
