[package]
name = "runtime"
version = "0.2.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.14.0"
lazy_static = "1.4.0"

[lib]
crate-type = ["staticlib", "rlib"]

[lints.clippy]
pedantic = "deny"
