[package]
name = "kyanite_builtins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "kyanite_builtins"
crate-type = ["cdylib"]

[lints.clippy]
pedantic = "deny"